image: registry.gitlab.com/passbolt/passbolt-ci-docker-images/android-app:latest

variables:
  ANDROID_HOME: "${PWD}/android-home"

# jobs need to be defined in a single stage in order to be executed in parallel
# conditions if a job is started for a particular commit/push are defined under 'rules' sections
stages:
  - build

verification:
  stage: build
  tags:
    - docker
  script:
    - ./gradlew --no-daemon --build-cache detekt ktlint lintDebug unitTest koverMergedHtmlReport licenseeRelease dependencyUpdates buildHealth
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "schedule"'
  artifacts:
    when: always
    expire_in: 72 hrs
    paths:
      - "**/reports/ktlint-report.xml"
      - "**/reports/detekt-report.xml"
      - "**/lint-results-*.html"
      - "**/test-results/**/TEST-*.xml"
      - build/reports/kover/html/
      - build/dependencyUpdates/dependecyUpdates.txt
      - build/reports/build-health-report.txt
    reports:
      junit: "**/test-results/**/TEST-*.xml"

release-internal-testing:
  stage: build
  tags:
    - docker
  script:
    - echo $QA_KEY | base64 -d > "${HOME}/qa.keystore"
    - python3 -m pip install -r gradle/requirements.txt
    - export GITLAB_BUILD_NUMBER="$(python3 gradle/gitlabBuildNumber.py "RELEASE_BUILD_NUMBER" ${CI_API_V4_URL} ${CI_PROJECT_ID} ${GITLAB_ACCESS_TOKEN})"
    - export FIREBASE_DIR="$HOME/.config/firebase"
    - install -d $FIREBASE_DIR
    - echo ${FIREBASE_SERVICE_KEY} | base64 --decode > "$FIREBASE_DIR/service_key.json"
    - >
      ./gradlew --no-daemon --build-cache -PwithGitlabReleaseNotes -PserviceKey="$FIREBASE_DIR/service_key.json"
      -Pandroid.injected.signing.store.file="${HOME}/qa.keystore"
      -Pandroid.injected.signing.store.password=$QA_KEYSTORE_PASSWORD
      -Pandroid.injected.signing.key.alias=$QA_KEY_ALIAS
      -Pandroid.injected.signing.key.password=$QA_KEY_PASSWORD
      assembleQa appDistributionUploadQa

  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
    - if: '$CI_COMMIT_BRANCH == "release"'
  artifacts:
    expire_in: 72 hrs
    paths:
      - "**/build/outputs/apk/**/*.apk"

release-production:
  stage: build
  tags:
    - docker
  script:
    - echo $PROD_KEYSTORE | base64 -d > "${HOME}/production.keystore"
    - python3 -m pip install -r gradle/requirements.txt

    - >
      ./gradlew --no-daemon
      -Pandroid.injected.signing.store.file="${HOME}/production.keystore"
      -Pandroid.injected.signing.store.password=$PROD_KEYSTORE_PASSWORD
      -Pandroid.injected.signing.key.alias=$PROD_KEY_ALIAS
      -Pandroid.injected.signing.key.password=$PROD_KEY_PASSWORD
      clean bundleRelease publishReleaseBundle

  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
  artifacts:
    expire_in: 72 hrs
    paths:
      - "**/build/outputs/bundle/release/*.aab"
